/*
 * KEYPAD.c
 *
 * Created: 2/7/2024 7:56:15 PM
 *  Author: Mina Waguih
 */ 


#include "KEYPAD.h"


void KEYPAD_voidInit(void)
{
	//DIO_voidSetPortDirection(KEYPAD_COL_PORT,PORT_OUTPUT);
	//DIO_voidSetPortValue(KEYPAD_COL_PORT,PORT_HIGH);
	DIO_voidSetPinDirection(KEYPAD_COL_PORT,KEYPAD_C0_PIN,PIN_OUTPUT);
	DIO_voidSetPinDirection(KEYPAD_COL_PORT,KEYPAD_C1_PIN,PIN_OUTPUT);
	DIO_voidSetPinDirection(KEYPAD_COL_PORT,KEYPAD_C2_PIN,PIN_OUTPUT);
	DIO_voidSetPinDirection(KEYPAD_COL_PORT,KEYPAD_C3_PIN,PIN_OUTPUT);
	
	DIO_voidSetPinValue(KEYPAD_COL_PORT,KEYPAD_C0_PIN,PIN_HIGH);
	DIO_voidSetPinValue(KEYPAD_COL_PORT,KEYPAD_C1_PIN,PIN_HIGH);
	DIO_voidSetPinValue(KEYPAD_COL_PORT,KEYPAD_C2_PIN,PIN_HIGH);
	DIO_voidSetPinValue(KEYPAD_COL_PORT,KEYPAD_C3_PIN,PIN_HIGH);
	
	//DIO_voidSetPortPullUpRes(KEYPAD_ROW_PORT);
	DIO_voidSetPinPullUpRes(KEYPAD_ROW_PORT,KEYPAD_R0_PIN);
	DIO_voidSetPinPullUpRes(KEYPAD_ROW_PORT,KEYPAD_R1_PIN);
	DIO_voidSetPinPullUpRes(KEYPAD_ROW_PORT,KEYPAD_R2_PIN);
	DIO_voidSetPinPullUpRes(KEYPAD_ROW_PORT,KEYPAD_R3_PIN);
}


u8 KEYPAD_u8GetPressedKey(void)
{
	u8 u8KPD_ROW_LOCAL = 0, u8KPD_COL_LOCAL = 0;
	u8 u8VALUE = 0;
	
	u8 KPD_ROW_PINS[] = {KEYPAD_R0_PIN,KEYPAD_R1_PIN,KEYPAD_R2_PIN,KEYPAD_R3_PIN};
	u8 KPD_COL_PINS[] = {KEYPAD_C0_PIN,KEYPAD_C1_PIN,KEYPAD_C2_PIN,KEYPAD_C3_PIN};
	
	u8 KPD_VALUES[KEYPAD_ROW_NUM][KEYPAD_COL_NUM] = KEYPAD_VALUES;
	
	for (u8KPD_COL_LOCAL=0; u8KPD_COL_LOCAL<KEYPAD_COL_NUM; u8KPD_COL_LOCAL++)
	{
		DIO_voidSetPinValue(KEYPAD_COL_PORT,KPD_COL_PINS[u8KPD_COL_LOCAL],LOGIC_LOW);
		
		for (u8KPD_ROW_LOCAL=0; u8KPD_ROW_LOCAL<KEYPAD_ROW_NUM; u8KPD_ROW_LOCAL++)
		{
			u8VALUE = DIO_u8GetPinValue(KEYPAD_ROW_PORT,KPD_ROW_PINS[u8KPD_ROW_LOCAL]);
			
			if (u8VALUE == KEYPAD_BUTTON_PRESSED)
			{
				_delay_ms(30);
				u8VALUE = DIO_u8GetPinValue(KEYPAD_ROW_PORT,KPD_ROW_PINS[u8KPD_ROW_LOCAL]);
				
				while (u8VALUE == KEYPAD_BUTTON_PRESSED)
				{
					u8VALUE = DIO_u8GetPinValue(KEYPAD_ROW_PORT,KPD_ROW_PINS[u8KPD_ROW_LOCAL]);
				}
				return KPD_VALUES[u8KPD_ROW_LOCAL][u8KPD_COL_LOCAL];
			}
		}
		
		DIO_voidSetPinValue(KEYPAD_COL_PORT,KPD_COL_PINS[u8KPD_COL_LOCAL],LOGIC_HIGH);
		
	}
	
	return KEYPAD_BUTTON_RELEASED;
}